-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th8 06, 2020 lúc 08:57 PM
-- Phiên bản máy phục vụ: 10.4.11-MariaDB
-- Phiên bản PHP: 7.4.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `hiphopland`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `event`
--

CREATE TABLE `event` (
  `id` int(50) NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp(),
  `image` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `host` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `event`
--

INSERT INTO `event` (`id`, `name`, `date`, `image`, `content`, `host`, `address`) VALUES
(2, 'sadf', '2020-08-05 08:25:25', 'anh', 'asdasdsadsad', 'hosted', 'address'),
(3, 'sự kiện', '2020-07-28 09:38:00', 'uploads/them-mot-doan-phim-ve-nhay-bi-tranh-luan-nhieu-nhu-rap-viet-vay-ket-cuc-chung-ta-muon-gi_335-20200806-114031.png', 'xxxxxx', '11111', 'aaaaa'),
(4, 'sự kiện 22', '2020-07-08 09:38:00', 'uploads/voi-wowy-neu-rap-viet-la-dich-den-cua-nam-2020-thi-bo-phim-rom-dai-dien-cho-mot-hanh-trinh-cua-anh_317-20200806-114121.jpg', 'sdsadsdsad', '222222', 'ddddd'),
(5, 'sự kiện 22', '2020-07-08 07:20:00', 'uploads/voi-wowy-neu-rap-viet-la-dich-den-cua-nam-2020-thi-bo-phim-rom-dai-dien-cho-mot-hanh-trinh-cua-anh_317-20200806-114238.jpg', 'sdsadsdsad', '222222', 'ddddd'),
(6, '', '0000-00-00 00:00:00', '', '', '', ''),
(9, 'dd', '2020-08-11 12:53:00', 'uploads/voi-wowy-neu-rap-viet-la-dich-den-cua-nam-2020-thi-bo-phim-rom-dai-dien-cho-mot-hanh-trinh-cua-anh_317-20200806-025317.jpg', 'aa', 'dd', 'â'),
(10, 'Halley Crew x Funke Bros Jam & Party', '2020-07-23 03:00:00', 'uploads/halley-crew-x-funke-bros-jam-party_9-20200806-035124.jpg', 'DAY 1 (Warmup day) - 27.03.2019  Graffiti Jam “Rock the Wall” 10am-4pm Bring your can and rock the wall with us  Breaking Workshop: Eddie Style (RockSoFresh - USA) x Bgirl Jilou (Jimekano - Germany) 3pm-4:30pm Price: 200.000 VND  Bboy Mouse (SAS Crew/ Floorgangz - Philipin) 4:30pm-6pm Price:200.000 VND   Pre-Party 9:00pm -12:00pm  ĐỊA ĐIỂM / LOCATION : Đà Nẵng - Việt Nam  ////////////////////////////////////////////////////////  DAY 2 (Main day) :  3 vs 3 Breaking ”Enter the cypher” 7 to smoke Breaking \"International vs Local\" Exihibition battles  Live funky band Live graffiti Live Rapshow : 3 đường ke  After party: Funke Bros Anniversary   THỜI GIAN / TIME: SATURDAY 28 Mar 2020 (2:00PM -2:00am)  ĐỊA ĐIỂM / LOCATION : Apocalypse Beach Club - 51 Võ Nguyên Giáp, Đà Nẵng, Việt Nam  Vé vào cửa / TICKET : Updating  ---------------------------  TRỌNG TÀI/ JUDGES: - Felix (Radikal Forze Crew/7$ - Singapore) - Mouse (MZK/Floorgangz/SAS - Philipine) - Eddie Style (Rock So Fresh - USA)  DJ: - DJ Slowz (RareJointz Crew) - DJ BenBlue (RareJointz Crew)  ////////////////////////////////////////////////////////  Day 3: FUNKE BROS 6TH ANNIVERSARY BEACH PARTY (HOSTED BY FUNKE BROTHERS)  THỜI GIAN / TIME: SUNDAY 29 Mar 2020 (07:00 PM -02:00 AM)  ĐỊA ĐIỂM / LOCATION : Đà Nẵng - Việt Nam  Các nhà tài trợ, Các Shop, nhãn hiệu… cần hợp tác, hỗ trợ, tài trợ và có nhu cầu mở gian hàng tại sự kiện xin liên hệ: ĐT : 0983311184 (BBoy Cfloor) Email: cfloor.halley@icloud.com', 'HALLEY CREW', 'Apocalypse Beach Club - 51 Võ Nguyên Giáp, Đà Nẵng, Việt Nam'),
(11, '\" Sống tích cực - Đẩy lùi dịch bệnh Corona \" Breaking & Freestyle Kidz Online', '2020-02-18 12:00:00', 'uploads/song-tich-cuc-day-lui-dich-benh-corona-breaking-freestyle-kidz-online_14-20200806-035423.jpg', '????Công Rùa Class và VanHoaDuongPho phát động cuộc thi nhảy Freestyle Kidz Online chia sẻ thông điệp \" Sống tích cực - Đẩy lùi dịch bệnh Corona \" ⛔️Với 2 Hạng mục thi : Bboy/Bgirl Kidz Online Freestyle Kidz Online  ????????Chuỗi ngày nghỉ tránh dịch Corona tiếp diễn kéo dài đối với toàn bộ học sinh trên cả nước !!! ????Hãy cùng nhau vượt qua những ngày nghỉ 1 cách tích cực hơn nhé !!! ⛔️Đối tượng tham gia : Dành cho các Dancer Kidz trên cả nước lứa tuổi từ lớp 9 trở xuống ⛔️⛔️⛔️Nội dung cuộc thi : Các thí sinh quay 1 clip nhảy tự do theo phong cách của mình và nói khẩu hiệu \" Sống tích cực - Đẩy lùi dịch bệnh Corona \" trong clip và gửi về mail congrua.93@gmail.com . Btc sẽ up clip trên trang Fanpage này ⛔️Cách tính điểm : Với nội dung lan tỏa thông điệp đến xã hội nên sẽ tính điểm trên clip nào có lượng tương tác cao nhất 1 like = 1 điểm 1 share kèm hashtag = 2 điểm #Congruaclass #Vanhoaduongpho #SongTichCuc #DayLuiDichBenhCorona ⛔️⛔️⛔️Tính trên clip được Up tại Fanpage Công Rùa Class ⏰Thời hạn nộp bài dự thi : 20h ngày 16/2 kèm hạng mục dự thi / tên thí sinh / nhóm hoặc lớp học của mình ⏳Thời hạn đăng tải clip dự thi : trong 2 ngày 17-18/2 ⏳Thời hạn voting chốt điểm : Chốt điểm và công bố kết quả lúc 12h trưa ngày Chủ Nhật 1/3 ????Giải thưởng mỗi hạng mục : ????Giải nhất : 1 triệu đồng tiền mặt + 1 hộp khẩu trang y tế ????3 giải cống hiến : 1 Mũ Snap Back + 1 hộp khẩu trang y tế ????????????Hãy cùng chia sẻ cuộc thi này đến toàn bộ mọi người kèm thông điệp ý nghĩa \" Sống tí', 'Công Rùa Class', 'oàn Quốc, Hoàn Kiếm, Hà Nội'),
(12, ' BGIRL VIRTUAL SUMMIT 2020', '0000-00-00 00:00:00', '', 'BGIRL VIRTUAL SUMMIT 2020  I. THỜI GIAN ???? Vòng loại: - Các BGirl bắt đầu gửi video từ 8/3/2020 - 29/3/2020 - BTC upload video 30/3/2020 – 31/3/2020 - Voting: 1/4/2020 – 4/4/2020 - Thông báo Top 8: 5/4/2020 ???? Top 8: - Các BGirl Top 8 bắt đầu gửi video từ 6/4/2020 - 11/4/2020 - BTC upload video 12/4/2020 – 13/4/2020 - Voting: 14/4/2020 – 18/4/2020 - Thông báo Top 4: 19/4/2020 ???? Top 4: - Các BGirl Top 4 bắt đầu gửi video từ 20/4/2020 - 25/4/2020 - BTC upload video 26/4/2020 – 27/4/2020 - Voting: 28/4/2020 – 2/5/2020 - Thông báo Top 4: 3/5/2020 ???? Chung kết: - 2 BGirl bắt đầu gửi video từ 4/5/2020 - 9/5/2020 - BTC upload video 10/5/2020 - Voting: 11/5/2020 – 16/5/2020 - Thông báo Winner: ????17/5/2020  II. NỘI DUNG & THỂ THỨC THI ĐẤU - Nội dung thi đấu: + Mỗi B-Girl sẽ thực hiện một video thể hiện kỹ năng nhảy Breaking của mình và gửi về cho BTC trong thời gian quy định. + BTC sẽ chọn ra 08 B-Girl có số điểm cao nhất từ vòng loại để vào Top 8. + 8 B-Girl chiến thắng sẽ tiếp tục thực hiện các video tiếp theo để thi đấu lần lượt vào Top 4 và chung kết. + Chia cặp đấu Top 8, Top 4 sẽ dựa theo video của B-Girl có số điểm cao nhất thi đấu với B-Girl có số điểm thấp nhất. - Thể thức thi đấu: + Thời lượng tối đa mỗi video không vượt quá 60 giây. + Video phải được quay một lần ổn định, không cắt ghép chỉnh sửa, không slo-mo, không sử dụng các hiệu ứng, không quay cận cảnh,… + Video phải được thực hiện trong thời gian gần đây nhất, trước thời điểm tham dự cuộc thi không quá 3 t', 'Vietnamese Bgirls', '42bis Lý Tự Trọng, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh, 1, Hồ Chí Minh'),
(13, ' Mini Battle Stay Home', '0000-00-00 00:00:00', '', 'Mini Battle StayHome là Battle về Sketch được diễn ra trong mùa nghỉ ở nhà phòng dịch Covid.  Giải dựa theo tiêu chí thả tim- thí Sinh được yêu thích nhất (Dựa vào bài viết được thả tim nhiều nhất - không tính like để tránh trường hợp spam like làm mất cân bằng cuộc thi) ????1 Giải nhất: -300k (Sun) - 06 chai zebra pro (House of paint) -1combo caps (House of paint) -1 tshirt (Max) ???? 1 Giải Nhì: -100k (Sun) -4 Chai Zebra + 1 Adapter (CSJ) -1 áo phông Undeadstock (HNBMG) ???? 1 Giải ba: -50k (Sun) -2 Chai Zebra (CSJ) -1 áo phông Undeadstock (HNBMG)  Giải Sketch có triển vọng nhất: ( Do nhà tài trợ lựa chọn): -50k (Sun) -3 Aqua marker Molotow (House of paint) -3 Black Liner Molotow (House of paint) -1 tshirt (Max) -1 áo phông Undeadstock (HNBMG)  Thời gian công bố kết quả : kết quả sẽ dựa vào số tim được thả trên bài dự thi đến hết ngày 15/4/2020', 'Team GraffitiVN và Đỗ Thế Thành', 'Giảng Võ, Ba Đình, Hà Nội'),
(14, 'Hanoi street culture battle.', '0000-00-00 00:00:00', 'uploads/hanoi-street-culture-battle_27-20200806-083922.jpg', '2020 là một năm có nhiều sự kiện thế giới ảnh hưởng đến Việt Nam nói chung và văn hóa đường phố Việt Nam nói riêng. Dịch bệnh Covid-19, phong trào##blacklivesmatter ảnh hưởng không nhỏ đến nhận thức và định hưởng về văn hóa của giới trẻ. Được sự kết hợp từ Nhà hát ca múa nhạc Thăng Long trực thuộc Sở Văn hóa và Thể thao Thành phố Hà Nội, nhóm nhảy #SINE một lần nữa mang đến một sân chơi, giao lưu dành riêng cho các bạn đang theo đuổi bộ môn #Bboying với tên gọi ', 'S.I.N.E', 'Hoàn Kiếm, Hà Nội'),
(15, 'Trượt ván - Đà Nẵng CFN 2020', '2020-08-03 06:45:00', 'uploads/truot-van-da-nang-cfn-2020_35-20200806-084648.jpg', 'Như vậy chỉ còn 5 ngày nữa là sự kiện Đà Nẵng CFN sẽ diễn ra. BTC chúng tôi chính thức công bố các hạng mục thi đấu và giải thưởng như sau :  ????OLLIE CAO  Giải nhất : -1 vocher Tattoo 4tr ( đến từ The Hangout ) -1 deck blank + Grip ( đến từ AE Skate Shop ) -1 giày ( đến từ Ladybugskateshop ) -1 áo ( đến từ RieNevan )  Giải nhì : -1 vocher piercing 2tr ( đến từ LUSIS ) -1 áo ( đến từ The Hangout ) -1 nón ( đến từ RieNevan )  ????OLLIE XA  Giải nhất : -1 vocher tattoo 4tr ( đến từ The Hangout ) -1 deck blank + Grip ( đến từ AE Skate Shop ) -1 giày ( đến từ Ladybugskateshop ) -1 áo ( đến từ RieNevan )  Giải nhì : -1 vocher piercing 2tr ( đến từ LUSIS ) -1 áo đến từ ( The Hangout ) -1 áo ( đến từ RieNevan )  ????ĐUA VÁN ( chỉ dành cho nữ các bạn )  Giải nhất : -1 vocher tattoo 4tr ( đến từ The Hangout ) -1 giày X – SK8 Nữ ( đến từ RieNevan ) -1 áo vans ( đến từ AE Skate Shop ) -2 vòng bi push and go ( đến từ Ladybugskateshop )  Giải nhì : -1 vocher piercing 2tr ( đến từ LUSIS ) -1 áo nike ( đến từ AE Skate Shop ) -1 áo ( đến từ The Hangout )  ????Game of skate NHÓM ( mỗi team cử ra hai người để thi đấu )  -2 giày SNAP ( đến từ RieNevan ) -2 deck ( đến từ Ladybugskateshop ) -200k/người ( đến từ AE Skate Shop )  ????HIPPY JUMB ( có 2 giải nhất nữ và nhất nam )  1st Nam : -Tạp chí Transworld ( đến từ AE Skate Shop ) -1 áo ( đến từ RieNevan )  1st Nữ : -1 áo vans ( đến từ AE Skate Shop ) -1 nón ( đến từ RieNevan )  ????GIVE AWAY :  -1 giày + ốp dt + wheel + sticker + tất toymachine ( đến từ Ladybugskateshop ) -5 hoodie ( đến từ RieNevan )  ----------------------------------  Vì đây là giải dành cho Newbie cho nên có 2 thể lệ điều kiện như sau, AE lưu ý đọc kĩ: - Chơi dưới 1 năm rưỡi - Chưa đạt giải thưởng nào trong bất kỳ 6 tháng trở lại đây. Và để thuận lợi cho BTC sắp xếp, AE checkin trước bằng cách điền vào form này nhé: https://forms.gle/27s7YPNU4iNBJuQN6  Artwork by : Minh Duc  Thông tin BTC:  ???? Ladybugskateshop: Facebook: https://www.facebook.com/ladybugskateshop/ Instagram: https://www.instagram.com/ladybugsk8shop/  ???? AE Skate Shop: Facebook: https://www.facebook.com/aeskateshop/ Instagram: https://www.instagram.com/aeskateshop/ Website: https://aeskate.com/  ???? RieNevan: Facebook: https://www.facebook.com/RieNevan/ Instagram: https://www.instagram.com/rienevan/ Website: https://rienevan.com/  ???? The Hangout Tattoo Studio & Barbershop Facebook: https://www.facebook.com/thehangout.tattoo.studio/ Instagram: https://www.instagram.com/thehangout.hoian/ Website: https://thehangouthoian.com/  ☠️ LUSIS: Facebbok: https://www.facebook.com/allbylus/ Instagram: https://www.instagram.com/lusis.piercing/  ???? XUA studio: Facebook: https://www.facebook.com/XUAstudio/ Instagram: https://www.instagram.com/xuastudio/ Website: http://xuastudio.com/', 'CFN - 09124750 34', ' Công viên Như Nguyệt, Hải Châu, Đà Nẵng');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `news`
--

CREATE TABLE `news` (
  `id` int(50) NOT NULL,
  `cid` int(10) NOT NULL,
  `title` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` timestamp(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `image` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `news`
--

INSERT INTO `news` (`id`, `cid`, `title`, `date`, `image`, `content`) VALUES
(21, 1, '10 kỹ thuật cơ bản trong trượt ván dành cho người mới bắt đầu', '2020-08-06 08:35:06.544361', 'uploads/10-ky-thuat-co-ban-trong-truot-van-danh-cho-nguoi-moi-bat-dau_339-20200806-103506.jpg', 'Nếu là người mới trượt ván, bạn sẽ luôn tự hỏi có những kỹ thuật nào nên học và làm quen với chiếc ván thế nào khi mới bắt đầu?  Đúng là trượt ván là một bộ môn thể thao không dễ dàng, vì nó cần rất nhiều sự luyện tập, đồng thời kiên trì với những cú ngã. Vì vậy các kỹ năng sau đây sẽ giúp bạn tìm hiểu những điều cơ bản về trượt ván và cách bạn có thể thực hiện các kỹ năng khác nhau trên ván trượt khi mới bắt đầu.  1/ Ollie:  Đây là một trong những kỹ thuật cơ bản, sẽ là kỹ thuật bạn nên học đầu tiên vì nó chính là cốt lõi của những kỹ thuật phức tạp hơn sau này.  2/ Nollie:  Tiếp theo chúng ta nên có Nollie, còn được hiểu là Nose Ollie. Thủ thuật này tương tự như Ollie, thay vì bật đuôi bạn sẽ bật bằng mũi ván.  3/ Shuvit và Pop Shuvit:  Đây là một trong những kỹ thuật khá phổ biến và ưa chuộng trong nhiều năm, là kỹ thuật kết hợp nhấn đuôi ván và nhảy, ván sẽ xoay 180* , đây là kỹ thuật cực dễ chỉ cần bạn thực hành nhiều lần thôi.  4/ Frontside 180*  Sau khi đã tập được Ollie và Pop shuvit, hãy nâng cao kỹ năng bằng kỹ thuật Frontside 180*, nhưng phải chắc chắn rằng bạn đã thực sự tự tin với những kỹ thuật trên. Bạn sẽ đặt chân ở vị trí tương tự Ollie, đánh 1 lực từ vai ra sau 180* kết hợp cùng hông và chân.  5/ Backside 180*:  Backside 180 là động tác kết hợp nhảy và xoay ván theo trước mặt 1 góc 180*. Đây là thủ thuật quan trọng nằm ở phần vai, nếu vai và hông của bạn không xoay đủ 180 thì sẽ khó mà thực hiện.  6/ Kickflip:  Đây là kỹ thuật khó nhất trong các trick cơ bản'),
(22, 1, 'Triển lãm Graffiti trên đồ Jeans nói lên sự thật \"Sự im lặng khi nhìn thấy bạo lực chính là bạo lực\"', '2020-08-06 08:36:37.059216', 'uploads/trien-lam-graffiti-tren-do-jeans-noi-ve-lich-su-phan-doi-bao-luc-cua-nguoi-da-mau_338-20200806-103637.jpg', 'Gần đây tại bảo tàng nghệ thuật Graffiti Miami - Hòa Kỳ, đã diễn ra buổi trưng bày các tác phẩm của một số nghệ sỹ đường phố với chủ đề \" Nghệ sỹ trong các cuộc biểu tình\". Nội dung được thể hiện trên chất liệu là đồ Jeans, xoay quanh vấn đề phân biệt chủng tộc và sự im lặng khi nhìn thấy bạo lực chính là bạo lực.  Trong đó có một số bản giới hạn được giới thiệu bởi các nghệ sỹ Graffiti đường phố nổi tiếng như Futura, Tristan Eaton và Cey Adams, văn hóa đường phố xin được gửi đến quý bạn đọc một số hình ảnh được in trên tác phẩm để cùng tham khảo.'),
(23, 1, 'Ước gì chiếc ván trượt một bánh này được bán đại trà tại Việt Nam', '2020-08-06 08:37:35.476575', 'uploads/uoc-gi-chiec-van-truot-mot-banh-nay-duoc-ban-tai-viet-nam_337-20200806-103735.jpg', 'Ra đời nhằm giúp đỡ khách hàng có thể đi lại thuận tiện giữa những khu đô thị đông đúc như New York, tuy nhiên 6 năm qua kể từ ngày có những ý tưởng và sản phẩm đầu tiên từ công ty mẹ, chiếc xe này vẫn chưa thấy bán tại Việt Nam.  Các bạn thấy rõ vẻ \"cool ngầu\" từ nó rồi phải không, dạng kết cấu đô thị của Việt Nam thật sự phù hợp với loại thiết bị này.  Tuy nhiên trên thực tế, giá thành và điện lưới cũng cần thêm thời gian để có thể sử dụng được. Một chiếc cơ bản có giá khoảng gần 1k USD chưa thuế, phí, hơn nữa di chuyển liên tục mà không xạc được, vác trên vai cũng \"nát người\".  Chắc cũng đành chịu thêm một thời gian nữa thôi, khi trở nên phổ biến, số lượng được sản xuất nhiều hơn có thể nó sẽ rẻ hơn, các trạm xạc cho xu hướng xe điện đang có trong kế hoạch của nhiều công ty lớn sắp hoàn thành. Lúc đó khả năng cao nó sẽ được bán đại trà.  Sẽ chất làm sao khi một Skater sử dụng thiết bị này, trên tay cầm ván trượt gỗ và đi trượt hàng ngày.'),
(24, 1, 'Cứ nói giày Vans \"hoa hòe\", nhưng những mẫu sau của Clarks cũng được \"tô\" không ít - Dành cho dân đư', '2020-08-06 08:39:18.664882', 'uploads/cu-noi-giay-vans-hoa-hoe-nhung-nhung-mau-sau-cua-clarks-cung-duoc-to-khong-it_336-20200806-103918.jpg', 'Giới mộ điệu giày không cần phán, thì Vans chắc chắn vẫn thuộc Top dẫn đầu trong các mẫu giày có thiết kế màu mè, đặc biệt trong các chiến dịch Collab.  Tuy nhiên để tiếp bước những phiên bản trước đây, 3 ngày tới BAPE x Clarks sẽ ra mắt một mẫu có sắc màu \"văn hoa\" không kém -  Wallabee and Desert Boot  Lần này là phối tông Camo, nhưng trong lịch sử thì những đôi các sắc màu sặc sỡ được dân đường phố yêu thích cũng rất nhiều.'),
(25, 1, 'Có một đoạn phim về nhảy bị tranh luận như Rap Việt, vậy kết cục chúng ta muốn gì?', '2020-08-06 08:41:18.636176', 'uploads/them-mot-doan-phim-ve-nhay-bi-tranh-luan-nhieu-nhu-rap-viet-vay-ket-cuc-chung-ta-muon-gi_335-20200806-104118.png', 'Tuần vừa qua Rap Việt có lẽ nóng hơn một chút so với King Of Rap, bởi ngoài các vấn đề về mô hình thi, thí sinh, giám khảo vv.. còn có thêm câu chuyện của MC Trấn Thành.  Gần như đồng thời trong thời gian này, mạng xã hội cũng nổi lên một hiện tượng cũng có nhiều tranh cãi khác, đó là hai vợ chồng người nông dân nhảy Shuffle Dance ở một thành phố nhỏ thuộc Triết Giang - Trung Quốc.  Tóm tắt thì hai vợ chồng cũng đã quay một số Clip liên quan đến Shuffle Dance, và trên màn hình hiện lên dòng chữ hai vợ chồng tập nhảy để vượt qua trầm cảm. Chính điều này là nguyên nhân dẫn đến một số phản biện, có người cho rằng đây chỉ là dàn dựng với mục đích cổ động và không có thật.  Ghép hai câu chuyện thành một vấn đề, để thấy rằng những người làm ra những chủ đề trên, đều có mục đích riêng, với nội dung sử dụng hình ảnh, tính chất của Hip Hop, văn hóa đường phố để thu hút giới trẻ.  Với đa số thì quan điểm chung cho rằng tích cực và giúp khuếch trương tốt lĩnh vực này. Đây có lẽ chính là mục tiêu chính mà tất cả các nhà sản xuất muốn hướng đến. Trên thực tế, dù đúng dù sai họ cũng đã bắt tay vào làm ra một cái gì đó cho cộng đồng.  Các mục tiêu tiếp theo có thể là quảng cáo thương mại, cổ động sống khỏe, giáo dục nghệ thuật vv...cũng khó nói trước tiếp theo còn có gì, bởi sự biến đổi trong tư duy nghệ thuật rất \"khó lường\".   Nhưng thực sự đừng quan tâm quá nhiều, chỉ biết rằng những phát ngôn trái chiều đưa ra lúc này, chỉ làm cho các sự kiện, hình ảnh như trên \"bốc\" lên thêm mà thôi.'),
(26, 2, 'Những vấn đề chẳng bao giờ bạn nghĩ đến, cho đến khi bắt đầu gia nhập văn hóa đường phố', '2020-08-06 08:43:09.412446', 'uploads/10-van-de-chang-bao-gio-ban-nghi-den-cho-den-khi-bat-dau-gia-nhap-van-hoa-duong-pho_333 (1)-20200806-104309.jpg', 'Khi đọc những dòng dưới đây, rất có thể bạn đã là một thành viên của nền văn hóa này. Nó đã biến đổi con người, cuộc sống, suy nghĩ của bạn rất nhiều phải không. Thực sự không dễ dàng khi gia nhập, bởi xung quanh toàn những điều kỳ dị và khác biệt so với xã hội thông thường. Nhưng tốt thôi, từ đây bạn sẽ là chính mình.  Và vấn đề đầu tiên bạn sẽ làm, đó là tìm hiểu sơ qua tất cả những gì liên quan để trang bị kiến thức, nhằm xác định bạn đang ở đâu trong một thế giới toàn điều quái dị. Có thể chưa bao giờ bạn đọc, xem quá nhiều thứ trong một khoảng thời gian ngắn như vậy. Nhưng nếu bạn đang làm, thì tức là bạn thích và thực sự đam mê với nó.  Sau đó khi chưa kịp hiểu nội tâm, suy nghĩ, hành động của những người trong cộng đồng, thì học cách ăn mặc của họ là thứ bạn gần như làm ngay lập tức. Thời trang đường phố là một phần nổi rất quan trọng mà ai mới vào cũng bị hớp hồn. Trên thực tế thì ai trong giới này ra đường cũng rất đau đầu khi nghĩ xem mình sẽ mặc gì.  Mặc đẹp rồi, bạn sẽ nghĩ về cơ thể mình, bên ngoài làn da, cơ bắp đã \"ổn\" chưa, còn bên trong phải thế nào, để có thể hoạt động liên tục như những người kia nhỉ? Bạn bắt đầu thay đổi môn thể thao, cách chơi và xu hướng, là tất cả hay chọn thể loại có thể chơi ngoài trời.  Nhưng \"nguy hiểm\" nhất là những thứ đó dẫn đến một suy nghĩ, đó là làm thế nào để ở ngoài trời nhiều hơn, có một số người đã thay đổi công việc, giờ giấc làm việc cho mục đích này.  Với những suy nghĩ trên, bạn cho rằng đó là từ bỏ các khuôn khổ cũ để'),
(27, 3, 'Tiệm xe độ của BBoy Electric - Điểm đến văn hóa của giới Hip Hop vùng cao', '2020-08-06 08:44:18.587735', 'uploads/tiem-xe-do-cua-bboy-electric-den-den-van-hoa-cua-gioi-hip-hop-vung-cao_326-20200806-104418.jpg', 'Tiệm xe \"Súp Lơ\" tại Thành phố Hòa Bình là điểm trung chuyển của giới yêu xe và Hip Hop, khi họ cần hỗ trợ, di chuyển trên các cung đường lên vùng cao phía Bắc. Những chiếc xe khi qua đây được chăm sóc bởi một thành viên của Candy Crew - BBoy Electric.  Là một người chơi cả BBoying và SkateBoarding, cho nên các sản phẩm được anh \"dựng\" nên luôn đậm chất nghệ sỹ, điểm đặc biệt là số lượng xe qua đây làm \"thẩm mỹ\" đều là dòng xe côn, có dáng vóc giản dị, nhưng mạnh mẽ giống như hai môn chơi này.  Xuất thân là một BBoy của Lucky Crew, từ năm 2007 là thành viên của Candy Crew - nhóm nhảy có từ năm 2004 tại Hòa Bình, chính vì vậy niềm đam mê của anh luôn gắn liền với văn hóa đường phố nơi đây. Do đó sự giao thoa này, được anh lấy làm cảm hứng tạo nên những chiếc xe cho các khách hàng của mình.  Những gì anh đã cống hiến cho Hip Hop Hòa Bình trong thời gian qua, một phần đưa Candy Crew trở thành một điểm đến không thể thiếu của cộng đồng nơi đây.  Do đó, chúng ta cùng hy vọng rằng, tiệm xe Súp Lơ sẽ có những bước phát triển lớn hơn, tạo nên thêm một cộng đồng nghệ thuật lớn mạnh nữa - Nghệ thuật chơi xe độ.'),
(28, 3, 'Ngã ngửa người với hai sợi dây chuyền Tupac trị giá 14 tỷ đồng', '2020-08-06 08:45:06.118919', 'uploads/nga-ngua-nguoi-voi-hai-soi-day-chuyen-tupac-tri-gia-14-ty-dong_325-20200806-104506.jpg', 'Mới đây cộng đồng Rap, Hip Hop, đặc biệt là các fan hâm mộ Tupac có dịp ngã ngửa người khi nhìn thấy hai sợi dây chuyền này. Sản phẩm đến từ Drake - Rapper đào hoa, thuộc nhóm rapper thế hệ mới, cùng với Nicki Minaj, Kendrick Lamar, những người nổi lên từ những năm 2010, những người có tầm ảnh hưởng đến nền nhạc Rap hiện đại và được coi là kế vị hai ngôi sao đã đạt đẳng cấp huyền thoại sống là Eminem và Jay-Z.  Drake vừa tiết lộ hai sợi dây chuyền kim cương mới nhằm vinh danh cố Rapper Tupac Shakur. Hai sợi dây chuyền này được sản xuất bởi thợ kim hoàn lâu đời Jason of Beverly Hills. Đây có thể nói là sợi dây chuyền mang đẳng cấp nghệ thuật, với mặt dây chuyền là chân dung Tupac được pha trộn với hình ảnh \"Vòng mạo gai\" của Chúa Jesus. Một phiên bản bandana màu xanh sử dụng vàng trắng và kim cương, còn phiên bản bandana màu đỏ thì sử dụng kim cương cùng màu vàng tự nhiên. Các chi tiết khác như vòng mạo gai, khuyên mũi mũi, nước mắt và khuyên tai đều gắn kim cương.  Mỗi mặt dây chuyền được ghép với một chuỗi kim cương 70 cara để đi cùng với nửa kilo vàng được sử dụng để làm cả hai mặt dây chuyền. Thời gian thực hiện cả hai sợi dây chuyền mất tổng cộng năm tuần (150 giờ làm việc) và hai sợi dây chuyền có giá 14 tỷ đồng.'),
(29, 3, 'Phiên bản ván trượt giới hạn 100 chiếc giữa Virgil Abloh và DGK', '2020-08-06 08:48:34.300773', 'uploads/phien-ban-van-truot-gioi-han-100-chiec-giua-virgil-abloh-va-dgk_311-20200806-104834.jpg', 'Một trong những Skater có ảnh hưởng nhất thế giới, Stevie Williams, cùng thương hiệu DGK của anh ấy đã kết hợp với ông trùm của làng thời trang đường phố Virgil Abloh cho ra một thiết kế ván trượt chỉ giới hạn 100 chiếc.  Chiếc ván phiên bản giới hạn này có mặt trên bằng gỗ đặc trưng và nhấn đậm Logo thương hiệu màu đen với dòng chữ ghi rõ sự hợp tác của Williams và Abloh. Phần dưới ván được sử dụng thiết kế Camo ngụy trang quân đội, có vẻ nét vẽ tay này được vẽ bởi chính Abloh và có chữ thương hiệu DGK màu đen rải rác ngẫu nhiên xung quanh hoa văn Camo.  Mỗi chiếc ván đều được khắc bằng laser với dòng chữ Abloh và số lượng sản xuất được đánh số từ 001 đến 100. Tất cả số tiền thu được từ lần hợp tác này giữa Virgil Abloh x DGK sẽ được quyên góp cho '),
(30, 2, 'Với Wowy - Nếu Rap Việt là đích đến của năm 2020 thì bộ phim Ròm giúp liên tưởng hành trình của cuộc', '2020-08-06 08:50:37.786941', 'uploads/voi-wowy-neu-rap-viet-la-dich-den-cua-nam-2020-thi-bo-phim-rom-dai-dien-cho-mot-hanh-trinh-cua-anh_317-20200806-105037.jpg', 'Nói về những gì đã trải qua trong cuộc sống, công việc của Rapper Wowy để có thể trở thành Huấn Luyện Viên tại Rap Việt 2020. Có lẽ dễ hiểu nhất, là gắn nó với những hình ảnh, sự việc diễn ra trong và bên ngoài \"Ròm\" - Bộ phim đã giành được giải \"New Currents\" tại Liên hoan phim quốc tế Busan lần thứ 24.  Wowy là một trong năm diễn viên chính và tác phẩm \"Chạy\" của anh là nhạc chủ đề của bộ phim này.  \"Sóng yên biển lặng\" không phải là cụm từ thích hợp để nói lên quá trình sản xuất, ra mắt và đoạt giải của \"Ròm\". Nếu theo dõi sát quá trình này, chúng ta cũng sẽ liên tưởng nó giống những gì mà Rapper Wowy đã trải qua để có thể trở thành Huấn Luyện Viên tại Rap Việt 2020. Mất khoảng hơn 7 năm để đến được Busan, thêm gần 1 năm xin phê duyệt để được công chiếu, đến gần ngày \"lên sóng\" tại Rạp thì tạm hoãn do dịch. Bộ phim đã và đang mang lại rất nhiều thách thức với cả Ekip và những người có liên quan đến Sinh mệnh của nó.  Với tất cả thì Ròm gần như là bộ phim đầu tay mà họ tham gia, theo nội dung của bộ phim thì họ giống như \"tất tay\" vào một con số ở thời điểm đó. Thời gian - Tiền Bạc và một thứ quan trọng hơn đó là Thanh xuân tuổi trẻ. Bạn đọc sẽ thấy rất bất ngờ hơn bởi ở những giai đoạn khởi đầu, thai nghén thì họ chỉ mới ở giai đoạn khoảng 20 tuổi, nhưng đều dám nghĩ dám làm.  Sự liên tưởng không hề quá, khi nói về Ròm bằng chất đường phố để phản ánh con đường của Wowy. Một Rapper được công nhận và đã trở thành người dẫn dắt giới trẻ tại Rap Việt 2020 trên truyền hình tới '),
(31, 2, 'Thời đi học lắm bi hài của trưởng nhóm đầu tiên - người sáng lập nhóm Ngón Chân Cái - Big toe Crew.', '2020-08-06 08:53:56.578617', 'uploads/thoi-di-hoc-lam-bi-hai-cua-truong-nhom-dau-tien-nguoi-sang-lap-nhom-ngon-chan-cai-big-toe-crew_315-20200806-105356.jpg', 'Theo như giới thiệu của BBoy Thành Lion T thì anh Phạm Anh Tuấn mới người thành lập và đặt tên cho nhóm Ngón Chân Cái - Big Toe Crew. Và hôm nay VHĐP tìm ra được một Clip thời đi học của anh thì phải? - Thật sự cười không nhặt được mồm.  Có lẽ sự tinh nghịch của các học trò luôn như vậy, để có các thế hệ Hip Hop cá tính như ngày nay.  Thực ra Clip chỉ là một bộ phim có anh Tuấn diễn xuất, tuy nhiên theo suy đoán dựa trên các tác phẩm có anh tham gia sau này thuộc Điện Ảnh Việt Nam, nó khá giống với tính cách và tạo nên sự thành công của anh bây giờ.  Một lần nữa cảm ơn BBoy Thành Lion T đã chia sẻ một thông tin hữu ích và khá thú vị về quá trình thành lập nhóm nhảy nổi tiếng Việt Nam - Ngón Chân Cái.'),
(32, 1, 'Hậu hôn nhân với Reebok, adidas cho ra đời hai mẫu cùng cha khác mẹ với \"chị cả\" Club C 85, khiến gi', '2020-08-06 08:54:52.117480', 'uploads/hau-hon-nhan-voi-reebok-adidas-cho-ra-doi-hai-mau-cung-cha-khac-me-voi-chi-ca-club-c-85-khien-gioi-yeu-giay-co-bi-hop-hon_330-20200806-105452.jpg', 'Tháng 8 của 15 năm trước, hôn ước giữa Reebok và adidas được tác thành, tạo thêm một đôi cánh giúp họ duy trì thế đối trọng đáng gờm với ông lớn khác trong ngành - Nike.  Cùng chiến lược, thông suốt tầm nhìn, rõ ràng các mẫu giày có thể đưa ra cùng nhau là không thiếu, tuy nhiên có hai mẫu giày mà giới yêu thích sự cổ điển luôn muốn ngắm nhìn hay sở hữu, đó là adidas Powerphase và adidas Continental 80.   Đây là hai mẫu có ngoại hình tương đối giống với người \"chị\" Reebok Club C 85 ra đời cách đây 35 năm.   Sự hoài cổ mang đến từ màu sắc trắng kem cùng với đế ngả màu, đây có lẽ là 3 mẫu được những người yêu thích sự cổ điễn quyết mua ngay từ ánh nhìn đầu tiên.  Nhân kỷ niệm 15 năm về chung một nhà, văn hóa đường phố xin gửi lại bạn đọc câu chuyện trên, hi vọng sẽ phần nào giúp các bạn có thêm được một sự lựa chọn, đặc biệt là những ai đang ở độ tuổi ngoài 30, đang kiếm tìm thêm một đôi giày thể thao chất đường phố cho bộ sưu tập của riêng mình.'),
(33, 1, 'Sau tập 1: King Of Rap giống cuộc thi, còn Rap Việt rõ vai trò một sân chơi thương mại', '2020-08-06 08:56:13.501906', 'uploads/sau-tap-1-king-of-rap-giong-cuoc-thi-con-rap-viet-ro-vai-tro-mot-san-choi-thuong-mai_329-20200806-105613.jpg', 'Sau 2 tháng công bố và vận hành sản xuất, tập đầu tiên của hai cuộc thi Rap lớn nhất trên truyền hình Việt Nam từ trước tới nay, đã chính thức công chiếu. King Of Rap và Rap Việt  Về tổng quan đây là hai chương trình được đầu tư công phu, để đưa Rap nói riêng và Hip Hop nói chung trở thành một sân chơi lớn, nghệ thuật chính thống. Bởi rất nhiều thí sinh tham gia đều chia sẻ:  \"Họ mong muốn có điều kiện biến Rap thành đam mê và cũng là sự nghiệp sau này của mình.\"  Sau tập 1, có lẽ người trong ngành Rap, cũng bắt đầu nhận ra, King Of Rap có dáng dấp của một cuộc thi hơn, còn Rap Việt có những dấu hiệu cho thấy, nó là một Show truyền hình thương mại.  Với khoảng gần 1.5 giờ đồng hồ, tối hôm qua, các giám khảo của King Of Rap chuyên tâm vào phân tích các kỹ thuật của thí sinh nhiều hơn, đồng thời các kỹ thuật trường quay không được sử dụng nhiều nhằm mô tả thực sự những gì diễn ra trong đó, tạo nên một không gian tương đối \"phủi\" phản ánh chính xác các góc biểu diễn của từng thí sinh.  Đồng thời, các thí sinh của King Of Rap cũng được cộng đồng cho rằng có chất lượng cao hơn với Sóc Nâu, Right, Ngắn vv..đậm chất \"ngầm\", có lẽ không dưng mà họ lại cùng tụ ở đây như vậy.  Cũng với thời lượng tương đương, thì Rap Việt chỉ xoay quanh một số ít thí sinh, còn lại tập trung vào sự giao lưu, tạo tình huống giải trí nhiều hơn từ các Huấn Luyện Viên, Giám Khảo đến từ giới Mainstream với các Rapper đến dự thi.  Bên cạnh đó âm thanh, hậu kỳ xử lý kỹ, giúp cho chương trình này tương đối sạch'),
(34, 1, 'Lý giải về việc không thể nhảy một thời gian dài - BBoy The End cho mọi người thấy ý chí chính là th', '2020-08-06 09:14:47.479229', 'uploads/ly-giai-ve-viec-khong-the-nhay-mot-thoi-gian-dai-bboy-the-end-cho-moi-nguoi-thay-y-chi-chinh-la-thu-giup-con-nguoi-vuot-qua-so-phan_328-20200806-111447.jpg', 'Cùng thời điểm này, những ngày cuối tháng 7 năm 2016. BBoy huyền thoại The End, '),
(35, 1, 'Phong cách ăn mặc của Rapper Đạt Maniac luôn khiến các \"đồng âm\" trầm trồ', '2020-08-06 08:58:54.920522', 'uploads/phong-cach-an-mac-cua-rapper-dat-maniac-khien-cac-dong-am-kho-bi_327 (1)-20200806-105854.jpg', 'Sự chau chuốt đến từng mi li mét các bộ trang phục của mình, khiến cho Đạt Maniac luôn tạo được sự khác biệt, ngay cả với những Rapper cùng trong nghề. Bên cạnh việc nổi tiếng với những tác phẩm Rap \"nhanh như gió\", có lẽ việc ăn mặc như thế nào cũng là một phần tạo nên hương vị của anh.  Cũng phải thôi, nghệ thuật biểu diễn trên sân khấu mà, sao có thể mặc xấu được. Thực sự phong cách thời trang của anh khiến rất nhiều người trầm trồ ngưỡng mộ.  Phong cách này sẽ còn được nhắc đến nhiều, nó là một phần quan trọng bên cạnh giọng hát của tài năng này. Ngoài các bức dưới đây, hãy luôn theo dõi mạng xã hội của anh để cập nhật thêm những bộ trang phục mới các bạn nhé và đừng quên \"khét\" nhất là mấy bộ có ở King Of Rap tới đây.'),
(36, 1, 'Bomb Rush Cyberfunk - Game đỉnh cao của văn hóa đường phố', '2020-08-06 08:59:50.131351', 'uploads/bomb-rush-cyberfunk-game-dinh-cao-cua-van-hoa-duong-pho_322-20200806-105950.jpg', 'Team Reptile - Nhóm phát triển đằng sau game \"Lethal League\" - vừa mới giới thiệu 1 video ngắn quảng bá cho một game mới có tên là \"Bomb Rush Cyberfunk\", Khi xem video này chúng ta thấy rất giống với game \"Jet Set Radio\" huyền thoại. Thậm chí đặc biệt hơn, âm nhạc của video game được viết bởi nhà soạn nhạc tài ba Hideki Naganuma của JSR.  Nhanh chóng đạt được danh tiếng như một người kế thừa tinh thần, Bomb Rush Cyberfunk đưa người chơi vào một thế giới, nơi bạn sẽ có thể nhảy hay làm những điều  điên rồ nhất trên đường phố và phun graffiti ở mọi nơi bạn đến. Một thế giới xuất phát từ suy nghĩ của Dion Koster, nơi các bạn được trang bị các thiết bị cá nhân, và đạt đến tầm cao mới của graffiti. Tại thế giới này, bạn có thể tham gia cypher, nhảy, vẽ, hay đối mặt với cảnh sát và tuyên bố yêu sách của bạn với một đô thị ngổn ngang, đổ nát trong một tương lai thay thế.  Hiện tại, chưa có ngày phát hành chính xác cho trò chơi này, nhưng Team Reptile nói rằng bạn có thể hy vọng nó sẽ ra mắt sớm vào năm 2021. Và chắc chắn đây sẽ là một trò chơi tuyệt vời cho những ai yêu thích Graffiti và văn hóa đường phố.'),
(37, 2, 'Nike Cortez có quá nhiều màu và không phải ai cũng biết dễ phối đồ nhất là màu gì', '2020-08-06 09:01:11.653475', 'uploads/nike-cotez-co-qua-nhieu-mau-va-khong-phai-ai-cung-biet-mau-san-xuat-dau-tien-cua-no-la-mau-gi_313-20200806-110111.jpg', 'Được bán ra thị trường vào năm 1972 cho đến nay trải qua thời gian dài phát triển với nhiều lần thiết kế, collab khác nhau. Nike Cortez được phối bởi rất nhiều màu sắc để luôn có hương vị mới trong mắt người chơi.   Nhưng có lẽ màu được nhiều người ưa chuộng và cũng là mẫu khởi thủy tốn nhiều công sức nghiên cứu nhất của ngài Bill Bowerman chính là màu đỏ trắng, đế có viền xanh nước biển dưới đây.  Với đa số thì giày màu trắng dễ tương thích với các loại quần áo, đặc biệt trong một thế giới năng động ngày nay, bạn có thể mang nó đi với đồ văn phòng giúp giảm bớt áp lực công việc.  Hơn nữa, hãy luôn nhớ rằng giữ cho nó luôn \"Fresh\" nhé các dân chơi đường phố, để có thể đẹp như tuổi đời gần 50 năm của Nike Cortez.'),
(38, 2, 'Một buổi chia sẻ, tư vấn kiến thức ', '2020-08-06 09:14:31.716533', 'uploads/mot-buoi-chia-se-kien-thuc-tu-thai-son-beatbox-tai-sai-gon-xem-nhieu-doc-nhieu-la-toi-quan-trong_312-20200806-111431.jpg', 'Hôm qua 25/7 tại một quán Cafe đường Cô Bắc - Quận 1 - Sài Gòn đã diễn ra buổi chia sẻ kiến thức, tư vấn khá thú vị từ Thái Sơn một Beatboxer/Producer nổi tiếng của Việt Nam.  Chủ đề xoay quanh việc tư vấn cho các bạn trẻ yêu thích nhạc Rap, một số giải pháp đơn giản để có thể bắt đầu sáng tác những bài hát yêu thích của riêng mình. Ngoài ra với mỗi ví dụ cụ thể, sẽ có các khán giả lên giao lưu và được hướng dẫn thực hành ngay loại nhạc đó, cách phối nhạc đó do Thái Sơn Beatbox tư vấn.  Sau khi trả lời nhiều câu hỏi như:  '),
(39, 2, 'Hai dự án khởi nghiệp Hip Hop xin gọi vốn bị thất bại, hãy cùng xem lý do để rút kinh nghiệm cho bản', '2020-08-06 09:03:19.653572', 'uploads/hai-du-an-khoi-nghiep-hip-hop-xin-goi-von-bi-that-bai-hay-cung-xem-ly-do-de-rut-kinh-nghiem-cho-ban-than-ban_308-20200806-110319.jpg', 'Một dự án được khởi tạo tại Mỹ bởi một người đàn ông 32 tuổi tên là Ali Riojas và một từ Anh - tác giả là sinh viên 21 tuổi tên là Phil \'Skill\' Barton. Họ có chung một kết cục là gọi vốn không thành công cho những ý tưởng rất tích cực của mình đối với cộng đồng Hip Hop.  Đối với Ali Riojas anh gọi số vốn là 15000 USD để phục vụ cho mục đích thuê máy quét ảnh, sau đó in thành sách bán. Nội dung trong đó lưu lại lịch sử hình thành của cộng đồng nhảy tại New York.   Còn đối với Phil \'Skill\' Barton, anh nhận thấy có rất ít các bộ phim tài liệu về BBoying tại Anh. Anh dự định làm vô số các phóng sự về cuộc sống, văn hóa của những nhóm nhảy đường phố tại đây, đồng thời đặc biệt nhấn mạnh việc đào tạo người khác hiểu và nhận thức tốt về Hip Hop. Trong đó, giúp một phần đưa ra ánh sáng định nghĩa \"BBoying là gì\".  Dự án của anh cần huy động khoảng 3000 USD và nó chỉ nhận được vỏn vẹn có 19 USD. Còn Ali Riojas anh nhận được 1 USD.  Tóm lại là hai dự án không nhận được số tiền cần thiết cho việc sao chụp, in ấn hoặc chi phí đi lại và duy trì nguồn lực thực hiện dự án. Do vậy được coi là thất bại, những chi phí này cũng được các nhà đầu tư nhìn nhận dưới góc độ - Hai Giám đốc dự án này đã không cảnh báo họ các rủi ro và thách thức trong suốt quá trình thực hiện. Có nghĩa là dễ dàng phát sinh khả năng mất vốn.  Chính vì vậy, không chỉ riêng trong lĩnh vực Hip Hop, với bất kể mô hình kinh doanh nào, nếu bạn không thể lường trước được các vấn đề tiềm ẩn trong đó, khả năng người khác ủng hộ'),
(40, 2, 'BBIC 2020 không thể diễn ra như dự kiến, vậy cùng gặp lại, xem ai là một trong những \"con hàng\" chơi', '2020-08-06 09:04:19.786668', 'uploads/bbic-2020-khong-the-dien-ra-nhu-du-kien-cung-gap-lai-mot-trong-nhung-con-hang-choi-footwork-kho-nhai-nhat-cua-giai-dau-nay_307-20200806-110419.jpg', 'Lại thêm một giải đấu nữa phải hoãn lại vì Covid 19. BBIC thường niên được dự kiến tổ chức vào cuối tháng 9 năm nay, tuy nhiên nó đã không thể diễn ra bởi Hàn Quốc là nơi dịch bệnh đang có nhiều dấu hiệu nghiệm trọng.  Đây là một giải đấu được mong chờ nhất thế giới hiện nay, có chất lượng tương đương BOTY, Red Bull BC One vv..bởi khả năng quy tụ những trọng tài, Breaker, Dancer vv.. xuất sắc nhất hành tinh.  Nhưng tất nhiên, chủ nhà Hàn Quốc cũng đóng góp những cao thủ không hề kém cạnh, trong đó chúng tôi muốn bạn gặp gỡ thông qua Videos dưới đây, một \"con hàng\" khó nhai nhất của giải đấu, chơi chuyên ngành Footwork - BBoy Mario.  Và đây cũng là một BBoy có thể chơi Toprock khá tốt và đã dùng thể loại này chiến thắng ở nhiều giải đấu Freestyle khác.'),
(41, 3, 'ường phố thích săn đồ độc phải không? Khuyến nghị bạn một điểm bán Streetwear cũ cực hay tại Sài Gòn', '2020-08-06 09:05:11.033147', 'uploads/dan-duong-pho-thich-san-do-doc-phai-khong-khuyen-nghi-ban-mot-diem-ban-streetwear-cu-cuc-hay-tai-sai-gon_310-20200806-110511.jpg', 'Fresh & Still by Lê An đã quá quen thuộc với những người anh em trong Hip Hop tại Sài Gòn, chính vì vậy nếu bạn là một người yêu thích thời trang đường phố, hãy yên tâm khi đến đây - Bạn sẽ tìm được một món đồ mà bạn thích.  Với 6 năm hoạt động của cửa hàng và kinh nghiêm hơn 10 năm \"thu gom\" của ông chủ có xuất thân trong giới Hip Hop. Những món đồ ở đây được phân loại và mang về bán theo đúng phân khúc của nó - Chất đường phố.  Sẽ không cần giới thiệu nhiều về một nơi lâu năm như vậy, nếu có nhã hứng mời các bạn đến với Fresh & Still by Lê An - 70 Nguyễn Sơn Hà, Phường 5, Quận 3 - TP Hồ Chí Minh để khuân đồ nhé.'),
(42, 3, 'Một vụ đạo ý tưởng Graffiti bị tay vẽ Nguyễn Hoàng Hiệp phát hiện', '2020-08-06 09:06:00.080329', 'uploads/mot-vu-dao-y-tuong-graffiti-bi-tay-ve-ties-phat-hien_309-20200806-110600.jpg', 'Sự việc nêu trên trong làng nghệ thuật cũng đã xảy ra không ít lần, còn giờ đây là một bức vẽ trong lĩnh vực Hip Hop, cụ thể là sao chép có sửa lại một bức vẽ Graffiti. Theo cách tay vẽ Nguyễn Hoàng Hiệp nói chuyện thì có vẻ đây là một người Việt Nam đã thực hiện \"phi vụ\" này.  Tác giả chắc cũng nằm trong cộng đồng và đã đọc được những cảnh báo này. Sẽ tệ hơn nhiều nếu đây là một tác phẩm vẽ cho khách hàng có thu phí - Câu chuyện nghệ thuật bị bán rẻ.  Sẽ ra sao với những anh em làm ăn chân chính khác, khi họ phải nghĩ ý tưởng mới hàng ngày, tạo nên giá trị thực sự và đang vật lộn đưa Graffiti trở thành một nghề nghiệp chính thống.  \"Con sâu đang làm rầu nồi canh nghệ thuật\"'),
(43, 2, 'Cứ nói Graffiti khó kiếm tiền, hãy xem một doanh nghiệp Việt Nam ngành này làm ăn thế nào', '2020-08-06 09:06:42.847981', 'uploads/cu-noi-graffiti-kho-kiem-tien-hay-xem-mot-doanh-nghiep-viet-nam-nganh-nay-lam-an-the-nao_302-20200806-110642.jpg', 'Cộng đồng Graffiti Việt Nam bắt đầu hình thành từ những năm 2003-2004 và định hình khá tốt trong khoảng 5 năm trở lại đây. Vốn dĩ nó có thể ổn định bởi những người phát triển nó đã có thể đưa được môn chơi này song hành cùng các loại hình thương mại.  Với nhiều người khi theo đuổi Graffiti họ \"khuôn\" nó là một môn chơi không hơn không kém, nhưng có một bộ phận để nuôi dưỡng được đam mê, họ sẽ phát triển nó theo xu hướng của các ngành nghề thương mại.  Và gần đây có một nhóm lập ra có tên là Xưởng Kiến, trên các kênh truyền thông của thành viên, đã đề cập đến vấn đề họ đã giúp khách hàng tạo nên điểm nhấn cho doanh nghiệp, cửa hàng của mình bằng các bức vẽ Graffiti.   Đây là một hình thức phối hợp tốt để giúp các loại hình Hip Hop được lan tỏa nhanh hơn và giúp những người chơi Hip Hop có thể tự chủ kinh tế cho chính mình, đồng thời có điều kiện tài đầu tư giúp được người khác phát triển theo.   Thực trạng của Graffiti giờ đã không còn khó làm ra tiền như trước đây nữa, bởi hệ sinh thái trong văn hóa đường phố đã mở rộng hơn rất nhiều. Các chuỗi Barbershop, cửa hàng quần áo, Dance Studio, Doanh nghiệp sản xuất phụ trợ cho giải trí vv... đã sinh ra rất nhiều. Tất cả họ cần ai đó cung cấp những ý tưởng giúp tổ chức của mình nổi bật và có hình thái riêng, đặc biệt là những phong cách theo nghệ thuật, thể thao giải trí vv...  Nếu theo dõi cách thức triển khai của nhóm Xưởng Kiến trong khoảng 1 tháng qua, các công trình công khai cũng khoảng 4-5 địa điểm. Họ đều tạo ra được màu sắc'),
(44, 3, '5 Điều không nên làm trước khi đi trượt ván', '2020-08-06 09:14:16.496615', 'uploads/5-dieu-khong-nen-lam-truoc-khi-di-truot-van_303-20200806-111416.jpg', 'Các bạn nghĩ rằng trượt ván chỉ là việc đứng lên chiếc ván của mình? nhưng những gì các bạn làm trước và trong khi trượt có tầm ảnh hưởng khá nhiều. Chính vì vậy:   '),
(45, 2, 'Câu chuyện ý nghĩa sau bức hình mà chỉ có dân Hip Hop mới cảm nhận được', '2020-08-06 09:13:15.944950', 'uploads/cau-chuyen-y-nghia-sau-buc-hinh-ma-chi-co-dan-hip-hop-moi-cam-nhan-duoc_304-20200806-110908.jpg', 'Một bức ảnh do Photographer Phạm Quang Chiến chụp, xứng đáng đoạt giải \"Photo of the Year\" của giải thưởng chụp hình Văn Hóa Đường Phố. Có thể nó sẽ rất bình thường như một bức ảnh chụp phố phường mà chúng ta thường thấy nhưng ẩn sau đó, nếu bạn biết câu chuyện phía sau thì bạn sẽ thấy bức ảnh này cực kì ý nghĩa.  Một góc chợ cóc với nét đẹp lao động thường ngày của Hà Nội trong không gian vỉa hè nhỏ hẹp, cùng tường vàng cũ nát, bong tróc hở những viên gạch đỏ. Những tờ giấy dán quảng cáo, khoan cắt bê tông, nón lá, áo hoa, ghế nhựa,...Mọi thứ thật Việt Nam. Nhưng đúng là bức hình sẽ chỉ dừng lại với vẻ đẹp mang tính đặc trưng đó nếu thiếu đi tác phẩm Graffiti chân dung của một nam thanh niên trên tường. Một tác phẩm Graffiti của nghệ sĩ Mate - Là một trong những Graffiti Writer sinh sống tại Việt Nam và anh cũng là người tạo nên nhiều tác phẩm truyền cảm hứng cho các Graffiti Writter tại Việt Nam. Chân dung của người mà Mate vẽ chính là BBoy Small River, một trong những BBoy mang tính biểu tượng cho Vietnamese BBoy, một BBoy vẫn đang không ngừng cống hiến cho nền văn hóa Breaking Hip Hop tại đây.  Chính sự ngẫu nhiên này đã mang lại điều đặc biệt hơn cho bức ảnh, khi tất cả cùng hoà lại với nhau tạo ra một không gian đẹp nôn nao đến khó tả của văn hoá đường phố Việt Nam.'),
(46, 3, 'Một quảng cáo mới nghi là của Converse, ý tưởng hay, ý nghĩa sâu và sử dụng nhân vật cũng rất \"đời\"', '2020-08-06 09:10:22.843153', 'uploads/mot-quang-cao-moi-nghi-la-cua-converse-y-tuong-hay-y-nghia-sau-va-su-dung-nhan-vat-cung-rat-doi_301-20200806-111022.jpg', 'Gần đây cộng đồng mạng chia sẻ nhau về một hình ảnh, hai vợ chồng cụ già hơn 84 tuổi là chủ một của một tiệm giặt đồ tại Đài Loan đi hai đôi giày Converse khá mới để lên hình.  Toàn bộ câu chuyện xoay quanh tài khoản IG mới lập trong tháng 6 này là lượt xem đột biến và sự \"cute ngầu\" của vợ chồng ông cụ.  Sẽ không có gì lạ, nếu như không có cách chia sẻ của tài khoản này, nội dung thì khá hay, đó là do họ là chủ tiệm giặt là, nên lấy lại các quần áo của Khách hàng không đến lấy từ 10 - 20 năm qua để mặc lại.  Cách phối đồ thì nhìn khá là lổn nhổn bất quy tắc, nhưng chỗ ăn điểm chính lại là thần thái và sự tương đồng của hai ông bà cụ trong những bức ảnh.  Trong đó có sự xuất hiện của hai đôi giày khá mới và tần suất trên ảnh hơi bất thường nên chúng ta có quyền nghi ngờ đây là một cách thức quảng cáo mới của Converse tại thị trường Đài Loan.  Nếu khớp các thông tin, nội dung với tuổi đời của mẫu giày nhìn giống Converse Chuck Taylors, thì rõ ràng đây là một ý tưởng khá hay, sâu sắc và tạo hiệu ứng tốt với hai nhân vật cũng chạc tuổi nhãn giày này.  Trên thực tế của góc nhìn thương mại, thì Converse với những mẫu đầu tiên cũng đã gần cả trăm năm, về cốt lõi không có nhiều thay đổi, chỉ là các điều chỉnh bên ngoài như chất liệu, màu sắc. Nếu như câu chuyện nêu trên là một quảng cáo thật sự, nó cũng đã nêu bật được ý nghĩa này, đó là:  \"Dù bạn ở lứa tuổi nào, không nên hoặc không thể thay đổi bên trong, thì hãy cố gắng luôn có một diện mạo mới tự tin, đẹp đẽ và thu hút ở bên ngo'),
(47, 3, 'Cậu bé 10 tuổi đánh bật các đàn anh – Kickflip 6 bậc huyền thoại tượng đài Lý Thái Tổ', '2020-08-06 09:12:16.967297', 'uploads/cau-be-10-tuoi-kickflip-6-bac-huyen-thoai-tuong-dai-ly-thai-to-danh-bat-cac-dan-anh_294-20200806-111216.jpg', 'Dạo gần đây, cư dân mạng và cộng đồng ván trượt đã một phen choáng ngợp trước màn trình diễn xuất thần của một cậu bé chỉ mới 10 đã dám Kickflip xuống con bậc dài huyền thoại Lý Thái Tổ tại Hà Nội.  Sáu bậc tại Lý Thái Tổ là con bậc dài huyền thoại của các an hem trượt ván tại Hà Nội, với độ dài siêu khủng mà không phải ai cũng nhảy được, đến cả những Skater lâu năm cũng ngán ngẩm. Vậy mà một cậu bé 10 tuổi đã chinh phục nó thành công.  Sau cú land Kickflip siêu đỉnh của cậu bé này, không ít người tò mò về cậu ấy. Mọi người hay gọi cậu là Bách Bé, năm nay chỉ mới 10 tuổi, không biết cậu bắt đầu ván trượt từ khi nào nhưng năm 2018 đã thấy cậu bé xuất hiện trong các clip trượt trên mạng xã hội.  Trong một sự kiện giải trượt Come Back To OldSchool vào tháng 5 vừa qua, Bách đã thi đấu Game Of Skate và vượt qua rất nhiều đàn anh để dành được giải nhì trước sự bất ngờ của mọi người.  Có thể thấy Bách thật sự có tài trong bộ môn này, mặc dù cơ sở vật chất về môn Trượt ván ở Việt Nam ta còn khá thiếu thốn, nhưng vẫn xuất hiện đâu đó những nhân tài như Bách. Mong rằng trượt ván tại Việt Nam ngày càng phát triển, và có nhiều sân chơi hơn để các cô, cậu nhóc như Bách có cơ hội làm rạng danh Skateboarding Việt Nam.'),
(48, 2, 'Bật mí tuổi nghề của 3/6 giảm khảo gạo cội tại sự kiện \"Ngày Hội Hip Hop Huế\"', '2020-08-06 09:12:58.131348', 'uploads/bat-mi-tuoi-nghe-cua-35-giam-khao-gao-coi-tai-su-kien-ngay-hoi-hip-hop-hue_300-20200806-111258.jpg', 'Khá là thú vị khi ban tổ chức Ngày Hội Hip Hop Huế - Huế Hip Hop Festival, giới thiệu ba vị giám khảo lại là những cái tên gạo cội của làng Hip Hop Việt Nam.  Đây sẽ là 3 trong tổng số 6 người sẽ chấm ở hai hạng mục Giám khảo STB \"City vs City\" và Kids 1vs1. Bên cạnh những \"ngôi sao\" trẻ tuổi như MT POP, CK Animation, C2Low, Sơn Clown, Dan The Man và Mai Tinh Vi tại một số thể loại khác.  Tuy nhiên điều mà các thí sinh thi đấu lần này, có thể không nhiều người biết, 3/6 vị giám khảo gạo cội nêu trên đều là thế hệ đầu tiên của Hip Hop Hà Nội và đã tham gia trong cộng đồng nhảy Việt Nam liên tục trong suốt 27 năm qua.  Với sự xuất hiện lần này, có thể nói là sự may mắn của Hip Hop Việt Nam khi bắt đầu có những OG đủ tâm và tầm đứng ra cầm cân nảy mực. Giúp cho những giải đấu thành công hơn.  Đồng thời, các thế hệ sau có thể thấy được những tấm gương vẫn đang bền bỉ, khiến cho họ thực sự vững tâm và sẽ cống hiến hết mình cho văn hóa đường phố tại nước ta.'),
(49, 3, 'Street Crew x Crowbar Academy x Big South Crew ra mắt Dance Camp Vũng Tàu 2020 cho học sinh nhí', '2020-08-06 09:16:35.364725', 'uploads/street-crew-x-crowbar-academy-x-big-south-crew-ra-mat-dance-camp-vung-tau-2020_285-20200806-111635.jpg', 'Lần đầu tiên sự kết hợp giữa ba doanh nghiệp liên quan đến Hip Hop, đã tạo nên một mô hình trại hè lý tưởng cho các bạn nhí khu vực phía Nam. Chương trình được tổ chức với thời lượng 3 ngày 2 đêm tại Vũng Tàu trong tháng 8 tới đây.  Trong suốt thời gian dự hội trại, các bạn nhỏ sẽ được tham gia các chương trình đào tạo ngắn hạn liên quan đến Vũ đạo, kỹ năng sống hoặc các cuộc thi để trải nghiệm khả năng vượt qua các thách thức bản thân và thể hiện tinh thần đoàn kết đội nhóm.   Với sự góp mặt của Street Crew - Một nhóm nhảy hơn 10 năm thành lập tại Vũng Tau và Big South Crew với 13 năm kinh nghiệm hoạt động tại Sài Gòn. Kết hợp với sự vận hành chuyên nghiệp của Crowbar Academy. Chắc chắn các bé sẽ có thêm nhiều kiến thức thú vị từ nền văn hóa Hip Hop lâu năm của Việt Nam.  Tròn 1 tháng nữa sự kiện sẽ diễn ra, hi vọng các bậc phụ huynh sẽ quan tâm cho con tham gia, để cùng hiểu rõ hơn những gì đang diễn ra trong Hip Hop và tại sao nó trở thành một một nghệ thuật, thể thao hấp dẫn đến như vậy.  Chúc sự kiện diễn ra tốt đẹp và mang lại thêm nhiều tài năng nhí cho văn hóa đường phố Việt Nam.'),
(50, 3, 'Đạo diễn của bộ phim trượt ván nổi tiếng MID90S, ra hai mẫu mới cùng adidas, đơn giản nhưng dễ \"nghi', '2020-08-06 09:17:17.966927', 'uploads/dao-dien-cua-bo-phim-truot-van-noi-tieng-mid90s-ra-hai-mau-moi-cung-adidas-don-gian-nhung-de-nghieng_278-20200806-111717.jpg', 'Jonah Hill lớn lên cùng phong trào trượt ván nước Mỹ những năm 1990, và giờ đây bên cạnh Pharrell Williams, hai \"ông sao\" dự sẽ là những người có tầm ảnh hưởng nhiều nhất đến mẫu giày siêu sao của adidas: Superstar  Và sau khi có xác nhận hợp tác với nhau đầu năm nay, dự kiến hai bên sẽ cùng phát hành 3 mẫu, thì ngày mai 7/11 mẫu đầu tiên ra mắt sẽ là adidas Superstar. Ngoài ra còn một mẫu Samba và một chưa được tiết lộ, vậy hãy cùng VHĐP ngắm trước hai mẫu này.  Sự khác biệt sẽ ở hai dòng chứ Superstar và Samba trên thân giày, hi vọng Samba sẽ sớm ra mắt, còn với Superstar bạn có thể đặt mua bắt đầu từ ngày mai trên các kênh phân phối của hãng.'),
(51, 3, 'Chống xạm da mùa hè, nữ Skater tự phát kiến ra một liệu phát dưỡng da hay bất ngờ', '2020-08-06 09:18:35.127150', 'uploads/sau-khi-that-nghiep-de-tiet-kiem-tien-mua-kem-duong-da-nu-skater-tu-phat-kien-ra-mot-lieu-phat-duong-da-hay-bat-ngo_291-20200806-111835.jpg', 'Các nữ Skater không chỉ chú tâm làm \"tricks\" mà họ còn một mối lo rất lớn ngoài kỹ thuật, đó chính là làn da của mình. Mới đây một nữ Skater người Sài Gòn sau một thời gian nghiên cứu, đã tự mày mò và phát kiến ra một liệu pháp giúp bảo vệ làn da dưới trời nóng, giúp cô ấy tự tin hơn khi trượt ván ngoài đường.  Đó là một liệu pháp áp dụng một số công thức ăn uống, cho người chơi thể thao dưới nắng và không tốn nhiều chi phí. Nó đặc biệt phù hợp với địa bàn nắng nóng phía Nam hoặc những nơi nắng nóng kéo dài. Vậy hãy cùng tham khảo công thức của cô ấy.  1/ Hãy ăn nhiều Bưởi, nó sẽ giúp bạn trữ nước cho da.  2/ Ăn nhiều trái Bơ, có hỗn hợp nhiều chất béo giúp tăng ẩm cho da.  3/ Bông Cải Xanh giúp da đàn hồi tốt và chống tia UV  4/ Quả Đào giúp tẩy da chết  Thật quá tốt, nó là một giải pháp giúp các nữ Skater đỡ ngại ra đường trong mùa hè này, hãy thử và chia sẻ nếu bạn cảm thấy nó thích hợp với cơ thể mình.'),
(52, 2, '\"Quỳ\" trước 02 BGirl Việt Nam gần 10 năm trước khiến giới BBoy trong nước cảm thấy ngại ngùng', '2020-08-06 09:19:58.005255', 'uploads/day-se-la-bgirl-viet-nam-duy-nhat-khien-gioi-bboy-trong-nuoc-cam-thay-chan-doi_290-20200806-111957.jpg', 'BGirl Mikua và X - Beauty gần 10 năm trước đã xoay đầu điên đảo và phải chăng đây là 02 BGirl khủng nhất trong lịch sử Breaking Việt Nam cho đến nay???  Mặc dù BGirl Việt Nam thế hệ bây giờ đã nâng cao trình độ kĩ năng nhưng đúng là không thể phủ nhận những kĩ năng của các thế hệ BGirl ngày xưa, đặc biệt là khu vực miền Nam. Chỉ tiếc là trong các thế hệ BGirl thời đầu thì hiện nay chắc chỉ còn BGirl Mikua là vẫn xuất hiện trong 1 số giải đấu gần đây. Chúng tôi hy vọng sẽ thấy nhiều hơn nữa các BGirl với nhiều kĩ năng khó để chứng minh một điều \"Phụ nữ có thể làm tất cả\".'),
(53, 1, 'Trong quảng cáo Pepsi, thấy nam thần Quốc Tít nhảy ít quá thì vào đây xem thêm nhé các chị em', '2020-08-06 17:27:48.161055', 'uploads/xem-quang-cao-pepsi-thay-nam-than-quoc-tit-nhay-it-qua-thi-vao-day-xem-them-nhe_324-20200806-112131.jpg', 'Có lẽ vài giây ngắn ngủi trong Pepsi Ngõ chưa làm bạn cảm thấy thỏa mãn phải không? chúng tôi sẽ bổ sung thêm một số Clip của Nam thần trong làng Dancer Hà Nội này cho các bạn chiêm ngưỡng dưới đây:Đây là một thành viên chủ chốt của Last Fire Crew - Hà Nội, ngoài ra được cộng đồng đánh giá cao với nhiều lần làm giám khảo tại các giải đấu.  Dự án với Pepsi vừa qua, sự góp mặt của anh cho thấy, cộng đồng Dancer đang được các nhãn hàng lớn chú ý và trở thành xu hướng của quảng cáo trong tương lai, đại diện một phần cho văn hóa đường phố lâu đời tại Việt Nam.  Trên đây chỉ là Clip, ngoài đời anh chàng cũng có nhiều góc chụp khá thú vị, hãy theo dõi FB cá nhân để hiểu thêm về Dancer này các bạn nhé.'),
(57, 1, 'MC Trấn Thành dẫn chương trình Rap Việt, cộng đồng Rap xảy ra nhiều tranh luận, vậy thực sự nên thế ', '2020-08-06 18:44:17.583818', 'uploads/mc-tran-thanh-dan-chuong-trinh-rap-viet-cong-dong-rap-xay-ra-nhieu-tranh-luan-vay-thuc-su-nen-the-nao_305-20200806-025140-20200806-084417.jpg', '?Công Rùa Class và VanHoaDuongPho phát động cuộc thi nhảy Freestyle Kidz Online chia sẻ thông điệp ');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `news_category`
--

CREATE TABLE `news_category` (
  `id` int(10) NOT NULL,
  `name` varchar(20) NOT NULL,
  `home` int(10) NOT NULL,
  `right` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `news_category`
--

INSERT INTO `news_category` (`id`, `name`, `home`, `right`) VALUES
(1, 'Tin tức', 0, 0),
(2, 'Kiến thức', 0, 0),
(3, 'Lối sống', 0, 0);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `event`
--
ALTER TABLE `event`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `event`
--
ALTER TABLE `event`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT cho bảng `news`
--
ALTER TABLE `news`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
